# Label PRs based on file changes
# Using actions/labeler@v5 syntax

'type: documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

'type: tests':
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - '**/*test*.py'

'type: dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'

'area: cli':
  - changed-files:
    - any-glob-to-any-file: 'aicode/cli/**/*'

'area: llm':
  - changed-files:
    - any-glob-to-any-file: 'aicode/llm/**/*'

'area: database':
  - changed-files:
    - any-glob-to-any-file: 'aicode/database/**/*'

'area: config':
  - changed-files:
    - any-glob-to-any-file: 'aicode/config/**/*'

'area: infrastructure':
  - changed-files:
    - any-glob-to-any-file:
      - 'aicode/infrastructure/**/*'
      - 'aicode/interfaces/**/*'

'type: ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '.gitignore'

'type: refactor':
  - changed-files:
    - any-glob-to-any-file: 'aicode/**/*'
    - all-globs-to-all-files:
      - '!tests/**/*'
      - '!**/*.md'
